<?php
/**
 * Template Name: Tiendas Online León
 * Description: Página comercial clara para vender por internet.
 */
get_header();
?>
<main id="primary" class="site-main bg-[#121826] text-slate-300">
<?php while (have_posts()) : the_post(); ?>
<article id="post-<?php the_ID(); ?>" class="empc-service-page empc-store-page max-w-7xl mx-auto px-6 py-20 lg:py-24 space-y-16">
  <section class="grid lg:grid-cols-[1.1fr_0.9fr] gap-12 items-start">
    <div class="space-y-6"><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-emerald-300">Para vender por internet</p><h1 class="text-4xl md:text-6xl font-bold text-white leading-tight">Si tu tienda es un lío, la gente no compra</h1><p class="text-xl text-slate-400 leading-relaxed">Ordenamos productos, pagos y pedidos para que se pueda comprar sin complicaciones. Te lo explicamos con palabras normales.</p><a href="<?php echo esc_url(home_url('/#contacto')); ?>" class="inline-flex items-center justify-center min-h-11 px-6 py-3 rounded-xl bg-emerald-400 text-[#121826] font-bold hover:brightness-110">Quiero vender por internet</a></div>
    <aside class="rounded-[2rem] border border-white/10 bg-[#1F2937]/50 p-6 md:p-8 shadow-2xl space-y-4"><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-emerald-300">Una tienda clara</p><h2 class="text-2xl font-bold text-white">Para vender sin perder al cliente por el camino</h2><ul class="space-y-3 text-slate-300"><li>• Para negocios que ya venden o quieren empezar.</li><li>• Productos, pagos y pedidos fáciles de entender.</li><li>• Una tienda usable desde el móvil.</li><li>• Sin promesas mágicas de ventas.</li></ul></aside>
  </section>
  <section class="grid md:grid-cols-3 gap-4" aria-label="Resumen del servicio"><div class="rounded-2xl border border-white/10 bg-[#1F2937]/50 p-5"><strong class="text-white">Para quién es</strong><p class="mt-2 text-slate-400">Negocios que quieren vender por internet o mejorar la tienda que ya tienen.</p></div><div class="rounded-2xl border border-white/10 bg-[#1F2937]/50 p-5"><strong class="text-white">Qué problema resuelve</strong><p class="mt-2 text-slate-400">Una tienda confusa donde el cliente no sabe cómo pagar o no se fía.</p></div><div class="rounded-2xl border border-white/10 bg-[#1F2937]/50 p-5"><strong class="text-white">Qué te llevas</strong><p class="mt-2 text-slate-400">Un camino claro desde que el cliente ve el producto hasta que paga.</p></div></section>
  <section class="space-y-6"><div class="max-w-3xl space-y-3"><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-emerald-300">Qué revisamos</p><h2 class="text-3xl md:text-4xl font-bold text-white">Una compra clara de principio a fin</h2><p class="text-slate-400 leading-relaxed">Miramos lo que ve el cliente y lo que necesitas tú para recibir y gestionar cada pedido.</p></div><div class="grid md:grid-cols-2 xl:grid-cols-3 gap-6"><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-emerald-300 text-xs font-bold">01</span><h3 class="text-xl font-bold text-white mt-2">Lo que vendes</h3><p class="text-slate-400 mt-2">Que se vea qué es, cuánto cuesta y si está disponible.</p></div><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-emerald-300 text-xs font-bold">02</span><h3 class="text-xl font-bold text-white mt-2">Cómo te pagan</h3><p class="text-slate-400 mt-2">Las formas de pago que ya uses; no se inventa ninguna.</p></div><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-emerald-300 text-xs font-bold">03</span><h3 class="text-xl font-bold text-white mt-2">El pedido</h3><p class="text-slate-400 mt-2">Qué recibe el cliente y cómo te llega a ti.</p></div><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-emerald-300 text-xs font-bold">04</span><h3 class="text-xl font-bold text-white mt-2">En el móvil</h3><p class="text-slate-400 mt-2">Se tiene que poder comprar sin ampliar la pantalla.</p></div><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-emerald-300 text-xs font-bold">05</span><h3 class="text-xl font-bold text-white mt-2">Gastos y condiciones</h3><p class="text-slate-400 mt-2">Envío, plazos y lo que no está incluido.</p></div><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-emerald-300 text-xs font-bold">06</span><h3 class="text-xl font-bold text-white mt-2">Después de pagar</h3><p class="text-slate-400 mt-2">Confirmación, dudas y qué hacer si algo falla.</p></div></div></section>
  <section class="rounded-3xl border border-emerald-300/20 bg-emerald-400/5 p-6 md:p-8 grid lg:grid-cols-[1.1fr_0.9fr] gap-8 items-start"><div><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-emerald-300">Lo importante</p><h2 class="text-3xl md:text-4xl font-bold text-white mt-2">La tienda tiene que servirte a ti y a quien compra</h2><p class="text-slate-400 mt-3 leading-relaxed">Te enseñamos qué se ha ordenado y qué necesitas aportar para que la tienda pueda funcionar en el día a día.</p></div><div class="rounded-2xl border border-white/10 bg-[#1F2937]/50 p-5"><strong class="text-white">Sin fórmulas mágicas</strong><p class="text-slate-400 mt-2">La tienda ayuda a vender, pero no sustituye los productos, la atención, los envíos ni las decisiones del negocio.</p></div></section>
  <section class="space-y-6"><div class="max-w-3xl space-y-3"><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-emerald-300">Cómo trabajamos</p><h2 class="text-3xl md:text-4xl font-bold text-white">Cuatro pasos para poner orden</h2></div><div class="grid md:grid-cols-2 gap-4"><div class="rounded-2xl border border-white/10 bg-slate-900/60 p-6"><span class="text-emerald-300 text-xs font-bold">01</span><h3 class="text-xl font-bold text-white mt-2">Mirada</h3><p class="text-slate-400 mt-2">Vemos si no tienes tienda, tienes un catálogo o está a medias.</p></div><div class="rounded-2xl border border-white/10 bg-slate-900/60 p-6"><span class="text-emerald-300 text-xs font-bold">02</span><h3 class="text-xl font-bold text-white mt-2">Orden</h3><p class="text-slate-400 mt-2">Decidimos qué hace falta ahora y qué puede esperar.</p></div><div class="rounded-2xl border border-white/10 bg-slate-900/60 p-6"><span class="text-emerald-300 text-xs font-bold">03</span><h3 class="text-xl font-bold text-white mt-2">Montaje</h3><p class="text-slate-400 mt-2">Productos, pagos y pedidos dentro de lo acordado.</p></div><div class="rounded-2xl border border-white/10 bg-slate-900/60 p-6"><span class="text-emerald-300 text-xs font-bold">04</span><h3 class="text-xl font-bold text-white mt-2">Comprobación</h3><p class="text-slate-400 mt-2">Hacemos una compra de prueba y revisamos que se entienda.</p></div></div></section>
  <section class="rounded-3xl border border-white/10 bg-slate-900/60 p-6 md:p-8"><div class="max-w-3xl space-y-3"><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-emerald-300">Límites del servicio</p><h2 class="text-3xl md:text-4xl font-bold text-white">Lo que tienes que saber antes de empezar</h2></div><ul class="mt-6 grid md:grid-cols-2 gap-3 text-slate-300"><li>• No prometemos un número de ventas.</li><li>• Los pagos dependen del banco o la herramienta que se contrate.</li><li>• Fotos, precios y productos los aportas tú, salvo que se contrate la redacción.</li><li>• Envíos, devoluciones y textos legales se definen contigo.</li><li>• No es un marketplace: es la tienda de tu negocio.</li></ul></section>
  <section class="space-y-3"><p class="text-sm text-slate-400">Si tu tienda ya está hecha con WooCommerce, también la revisamos.</p></section>
  <section class="rounded-[2rem] border border-emerald-300/20 bg-emerald-400/5 p-6 md:p-8 flex flex-col md:flex-row md:items-center md:justify-between gap-6"><div><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-emerald-300">Siguiente paso</p><h2 class="text-3xl md:text-4xl font-bold text-white mt-2">¿Quieres que tu tienda funcione de verdad?</h2><p class="text-slate-400 mt-3">Cuéntanos qué vendes y vemos cómo montarlo.</p></div><a href="<?php echo esc_url(home_url('/#contacto')); ?>" class="inline-flex items-center justify-center min-h-11 px-6 py-3 rounded-xl bg-emerald-400 text-[#121826] font-bold hover:brightness-110">Quiero vender por internet</a></section>
</article>
<?php endwhile; ?>
</main>
<?php get_footer(); ?>
