<?php
/** Template Name: Diseño Web León Humanizado */
get_header(); ?>
<main id="primary" class="site-main bg-[#121826] text-slate-300">
<?php while (have_posts()) : the_post(); ?>
<article id="post-<?php the_ID(); ?>" class="empc-service-page empc-design-page max-w-7xl mx-auto px-6 py-20 lg:py-24 space-y-16">
<section class="grid lg:grid-cols-[1.1fr_0.9fr] gap-12 items-start"><div class="space-y-6"><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-[#E29595]">Webs para explicar lo que haces</p><h1 class="text-4xl md:text-6xl font-bold text-white leading-tight">Si tu web no se entiende, no te escriben</h1><p class="text-xl text-slate-400 leading-relaxed">Te hago una página o una web de empresa que diga qué ofreces, para quién y cómo contactarte. Sin que tengas que saber cómo está hecha.</p><a href="<?php echo esc_url(home_url('/#contacto')); ?>" class="inline-flex items-center justify-center min-h-11 px-6 py-3 rounded-xl bg-[#E29595] text-[#121826] font-bold">Quiero una web que se entienda</a></div><aside class="rounded-[2rem] border border-white/10 bg-[#1F2937]/50 p-6 md:p-8 shadow-2xl space-y-4"><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-[#E29595]">Una web clara</p><h2 class="text-2xl font-bold text-white">Para que tu negocio se entienda antes de pedirte más información</h2><ul class="space-y-3 text-slate-300"><li>• Para negocios que necesitan presentar sus servicios.</li><li>• Una web cómoda de leer en el móvil.</li><li>• Un siguiente paso visible para contactar.</li><li>• Sin elegir una herramienta antes de conocer tu caso.</li></ul></aside></section>
<section class="grid md:grid-cols-3 gap-4" aria-label="Resumen del servicio"><div class="rounded-2xl border border-white/10 bg-[#1F2937]/50 p-5"><strong class="text-white">Para quién</strong><p class="mt-2 text-slate-400">Negocios que necesitan explicar qué hacen y facilitar el contacto.</p></div><div class="rounded-2xl border border-white/10 bg-[#1F2937]/50 p-5"><strong class="text-white">Qué problema aborda</strong><p class="mt-2 text-slate-400">Una web que no deja claro el servicio, el público o la forma de contactar.</p></div><div class="rounded-2xl border border-white/10 bg-[#1F2937]/50 p-5"><strong class="text-white">Qué te llevas</strong><p class="mt-2 text-slate-400">Una estructura comprensible y un alcance definido antes de empezar.</p></div></section>
<section class="space-y-6"><div class="max-w-3xl space-y-3"><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-[#E29595]">Qué revisamos</p><h2 class="text-3xl md:text-4xl font-bold text-white">Una web pensada para quien la visita</h2><p class="text-slate-400 leading-relaxed">Ordenamos lo que necesita entender una persona antes de llamarte o escribirte.</p></div><div class="grid md:grid-cols-2 xl:grid-cols-3 gap-6"><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-[#E29595] text-xs font-bold">01</span><h3 class="text-xl font-bold text-white mt-2">Una página o varias</h3><p class="text-slate-400 mt-2">A veces basta una; otras veces hacen falta empresa, servicios y contacto.</p></div><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-[#E29595] text-xs font-bold">02</span><h3 class="text-xl font-bold text-white mt-2">Qué haces y para quién</h3><p class="text-slate-400 mt-2">Lo primero que se lee, no un texto genérico.</p></div><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-[#E29595] text-xs font-bold">03</span><h3 class="text-xl font-bold text-white mt-2">Cómo te contactan</h3><p class="text-slate-400 mt-2">Formulario, teléfono o lo que ya uses; solo canales reales.</p></div><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-[#E29595] text-xs font-bold">04</span><h3 class="text-xl font-bold text-white mt-2">En el móvil</h3><p class="text-slate-400 mt-2">Se tiene que leer y pulsar sin ampliar la pantalla.</p></div><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-[#E29595] text-xs font-bold">05</span><h3 class="text-xl font-bold text-white mt-2">Lo que se ve primero</h3><p class="text-slate-400 mt-2">Nombre, servicio y siguiente paso, sin rodeos.</p></div><div class="rounded-3xl border border-white/10 bg-[#1F2937]/30 p-6"><span class="text-[#E29595] text-xs font-bold">06</span><h3 class="text-xl font-bold text-white mt-2">Qué puedes cambiar tú</h3><p class="text-slate-400 mt-2">Textos y fotos básicas, sin depender de nadie para un horario.</p></div></div></section>
<section class="rounded-3xl border border-[#E29595]/20 bg-[#E29595]/5 p-6 md:p-8"><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-[#E29595]">Una decisión sencilla</p><h2 class="text-3xl md:text-4xl font-bold text-white mt-2">Si solo necesitas una página para empezar, lo vemos en el presupuesto</h2><p class="text-slate-400 mt-3 leading-relaxed">Una web con más páginas se valora según lo que tenga que explicar tu negocio. No necesitas saber con qué herramienta está hecha.</p></section>
<section class="space-y-6"><div class="max-w-3xl space-y-3"><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-[#E29595]">Cómo trabajamos</p><h2 class="text-3xl md:text-4xl font-bold text-white">Cuatro pasos para que la web cumpla su función</h2></div><div class="grid md:grid-cols-2 gap-4"><div class="rounded-2xl border border-white/10 bg-slate-900/60 p-6"><span class="text-[#E29595] text-xs font-bold">01</span><h3 class="text-xl font-bold text-white mt-2">Alcance</h3><p class="text-slate-400 mt-2">Vemos qué necesita tu negocio ahora, no una web enorme por defecto.</p></div><div class="rounded-2xl border border-white/10 bg-slate-900/60 p-6"><span class="text-[#E29595] text-xs font-bold">02</span><h3 class="text-xl font-bold text-white mt-2">Estructura</h3><p class="text-slate-400 mt-2">Ordenamos páginas, textos base y cómo se contacta contigo.</p></div><div class="rounded-2xl border border-white/10 bg-slate-900/60 p-6"><span class="text-[#E29595] text-xs font-bold">03</span><h3 class="text-xl font-bold text-white mt-2">Puesta en marcha</h3><p class="text-slate-400 mt-2">Se publica y se comprueba en móvil y ordenador.</p></div><div class="rounded-2xl border border-white/10 bg-slate-900/60 p-6"><span class="text-[#E29595] text-xs font-bold">04</span><h3 class="text-xl font-bold text-white mt-2">Entrega</h3><p class="text-slate-400 mt-2">Te explico qué tienes y qué puedes tocar.</p></div></div></section>
<section class="rounded-3xl border border-white/10 bg-slate-900/60 p-6 md:p-8"><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-[#E29595]">Límites del servicio</p><h2 class="text-3xl md:text-4xl font-bold text-white mt-2">Lo que queda fuera</h2><ul class="mt-6 grid md:grid-cols-2 gap-3 text-slate-300"><li>• No incluye tienda online; es otro servicio.</li><li>• No incluye aparecer los primeros en Google.</li><li>• No incluye ficha de Google salvo que se acuerde.</li><li>• Logo, fotos y textos largos los aportas tú, salvo redacción contratada.</li><li>• No hay plazos mágicos ni una web igual para todos.</li></ul></section>
<section class="rounded-[2rem] border border-[#E29595]/20 bg-[#E29595]/5 p-6 md:p-8 flex flex-col md:flex-row md:items-center md:justify-between gap-6"><div><p class="text-[11px] font-bold uppercase tracking-[0.25em] text-[#E29595]">Siguiente paso</p><h2 class="text-3xl md:text-4xl font-bold text-white mt-2">Cuéntame qué tiene que explicar tu web</h2><p class="text-slate-400 mt-3">Indica qué haces, para quién y cómo quieres que contacten contigo.</p></div><a href="<?php echo esc_url(home_url('/#contacto')); ?>" class="inline-flex items-center justify-center min-h-11 px-6 py-3 rounded-xl bg-[#E29595] text-[#121826] font-bold">Quiero una web que se entienda</a></section>
</article>
<?php endwhile; ?></main><?php get_footer(); ?>
